In [2]:
import numpy as np
def create_polynomial_features(X, degree=2):
    """Creates the polynomial features.
    
    Args:
        X: A numpy array for the data.
        degree: An integer for the degree of the generated polynomial function.
    """
    X_new = X
    for d in range(2, degree+1):
        X_new = np._c(X_new , np.power(X,d))
    return X_new

X = np.array([[1], [2], [3]])


In [4]:
def create_polynomial_features(X, degree=2):
    """Creates the polynomial features.
    
    Args:
        X: A numpy array for the data.
        degree: An integer for the degree of the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        print(X_new)
        print(X_mem)
        print("________________-")
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

X = np.array(  [[1 , 2] ,
                [2 , 3] ,
                [3 , 4]])

degree = 2

print(create_polynomial_features(X, degree))

[]
________________-
[array([1, 2, 3]), array([1, 4, 9])]
________________-
[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]
